"""Regenerate the prioritized crosswalk review worksheet.

Run from the repo root (any Python 3.11+, stdlib only):
    python3 scripts/build_review_queue.py

Writes data/annotations/crosswalk_review_queue.md — a human review aid that
orders every Sufinama match record by its top candidate score. It changes no
data: match records stay `needs_review` until a human classifies them.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "data" / "annotations" / "crosswalk_review_queue.md"

SOURCES = [
    ("kaafi", REPO_ROOT / "data" / "context" / "source_matches.jsonl"),
    ("non-kaafi", REPO_ROOT / "data" / "context" / "sufinama_text_source_matches.jsonl"),
]

BANDS = [
    ("Exact (score 1.0) — auto-merged into clusters; confirm the merge", 1.0, 1.01),
    ("Strong (0.85–0.99) — review these first", 0.85, 1.0),
    ("Moderate (0.60–0.85)", 0.60, 0.85),
    ("Weak (< 0.60) — likely distinct works, but confirm", -1.0, 0.60),
]


def main() -> int:
    rows = []
    for corpus, path in SOURCES:
        if not path.exists():
            print(f"missing {path}", file=sys.stderr)
            return 1
        for line in path.read_text(encoding="utf-8").splitlines():
            record = json.loads(line)
            candidates = record.get("candidate_poems") or []
            top = candidates[0] if candidates else {}
            score = float(top.get("score") or 0.0)
            signals = ", ".join(sorted(top.get("signals", {}))) if top else ""
            rows.append(
                {
                    "corpus": corpus,
                    "item": record["source_item_id"],
                    "url": record.get("source_url") or "",
                    "top_poem": top.get("poem_id", "—"),
                    "score": score,
                    "signals": signals,
                    "n_candidates": len(candidates),
                }
            )

    lines = [
        "# Crosswalk Review Queue",
        "",
        "Generated by `scripts/build_review_queue.py` — regenerate after any",
        "crosswalk rebuild; do not edit by hand. Classify each record in its",
        "match file (`match_status`: exact_witness / variant / excerpt /",
        "possible / unmatched); this worksheet only orders the work.",
        "Devanagari-signal scores are approximate transliteration evidence,",
        "capped at 0.98 by design.",
        "",
    ]
    for band_title, low, high in BANDS:
        band_rows = sorted(
            (r for r in rows if low <= r["score"] < high),
            key=lambda r: (-r["score"], r["item"]),
        )
        lines.append(f"## {band_title} ({len(band_rows)})")
        lines.append("")
        if not band_rows:
            lines.append("None.")
            lines.append("")
            continue
        lines.append("| corpus | source item | top candidate | score | signals | url |")
        lines.append("|---|---|---|---|---|---|")
        for r in band_rows:
            lines.append(
                f"| {r['corpus']} | {r['item']} | {r['top_poem']} | {r['score']:.4f} "
                f"| {r['signals']} | {r['url']} |"
            )
        lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(rows)} records)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
